### ISSUE TITLE
send along URL Search Params with redirect

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-html-pipeline#106]
(i am not sure if this is the right repo)
... on a redirect that is setup with the redirect spreadsheet, it would be great if on a redirect the query params are sent along in the `location` header.

so something that redirects from `/from?test=1` would be redirected to `/to?test=1`

**Comment by stefan-guggisberg** [comment]
Thanks @trieloff for the fix. Your fix is broader than the issue at hand, i.e. all redirect responses in general are processed to include the request query params.  I don't know whether that's desirable or not. In order to avoid potential side effects I have narrowed down the fix to just redirects originating from the `redirects` spreadsheet. BTW: I've checked `querystring.clean`: It doesn't handle/normalize multiple `?`, e.g. `querystring.clean("index?foo=bar" "?" "baz=bang")` returns `/index?foo=bar?baz=bang`.

I have activated the change in v137: https://manage.fastly.com/configure/services/7TvULgs0Xnls4q3R8tawdg/diff/136,137

@tripodsan I don't think anything needs to be changed in `helix-html-pipeline`.

**Comment by tripodsan** [comment]
> @tripodsan I don't think anything needs to be changed in helix-html-pipeline.

right.

**Comment by stefan-guggisberg** [comment]
Turns out to be more complicated ... 

We can't fix it on `hlx.page` since query params are conditionally stripped on `hlx.live` and therefore they won't be available on `hlx.page`. 

I suggest we fix it on `*.hlx.live`. 

@trieloff @davidnuescheler @tripodsan Thoughts?

**Comment by davidnuescheler** [comment]
i think a fix that's exclusively on `.live` probably works for the issue at hand, however i think that keeping `.live` and `.page` the same would be desirable as well. so maybe we could do it in both places?

**Comment by stefan-guggisberg** [comment]
> however i think that keeping .live and .page the same would be desirable as well. so maybe we could do it in both places?
ok

**Comment by stefan-guggisberg** [comment]
fixed:
.live v59: https://manage.fastly.com/configure/services/1PluOUd9jqp1prQ8PHd85n/diff/58,59
.page v139: https://manage.fastly.com/configure/services/7TvULgs0Xnls4q3R8tawdg/diff/138,139
