### ISSUE TITLE
add option to prevent generation of og:image & twitter:image tag

### ISSUE THREAD

**Issue by vhargrave** [adobe/helix-html-pipeline#210]
**Is your feature request related to a problem? Please describe.**
All sites, use image in metadata to populate og:image.
In Helix/Franklin code, fallback is the first image found. Sometimes though, we don't want og:image or twitter:image to be populated, since having this metadata prevents the page from receiving a video SEO ranking. 
It would therefore be nice to disable the generation of this metadata with something like an "off" statement, but that doesn't exist yet. 

**Additional context**
More details in (internal ticket) MWPW-117964.

**Comment by davidnuescheler** [comment]
if this is SEO related, then a client-sided solution should work for these edge cases, right?
usually the process is that we wait for widespread adoption in projects, before moving a feature into the product (via boilerplate) and then from boilerplate into the pipeline... 

let us know if you need help for the client-sided solution, which should also validate that it yields the appropriate results in SEO... given the "magic" that's at play with video indexing and all the attempt to influence things in the Adobe Express project, i think we should really make sure that we see the expected results.

**Comment by auniverseaway** [comment]
@davidnuescheler Similar to client-side JS not executing for fixing og:url to add `.html`, the same is the case here. We cannot remove an image if an author uses some sort of pattern like, `image | off` because JS doesn't get executed during link expansion

You can see the JIRA ticket of the original here: https://jira.corp.adobe.com/browse/MWPW-117964

I never thought Open Graph was related to SEO results, so Sharon may need to clarify.

@rofe did something on Express for a similar problem. Maybe he can also chime in here with his thoughts.

**Comment by rofe** [comment]
On Express, the problem was SEO (i.e. Google) related, and the client side soution (the value `--none--` would trigger the removal of the meta tag) worked like a charm.

@auniverseaway @vhargrave
